// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID        int64              `db:"id" derived:"authors.id" json:"id"`
	Name      string             `db:"name" derived:"authors.name" json:"name"`
	Bio       pgtype.Text        `db:"bio" derived:"authors.bio" json:"bio"`
	CreatedAt pgtype.Timestamptz `db:"created_at" derived:"authors.created_at" json:"created_at"`
}

type Post struct {
	ID        int64              `db:"id" derived:"posts.id" json:"id"`
	AuthorID  int64              `db:"author_id" derived:"posts.author_id" json:"author_id"`
	Title     string             `db:"title" derived:"posts.title" json:"title"`
	Body      pgtype.Text        `db:"body" derived:"posts.body" json:"body"`
	Views     int64              `db:"views" derived:"posts.views" json:"views"`
	CreatedAt pgtype.Timestamptz `db:"created_at" derived:"posts.created_at" json:"created_at"`
}
