// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID        int64              `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Bio       pgtype.Text        `db:"bio" json:"bio"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Post struct {
	ID        int64              `db:"id" json:"id"`
	AuthorID  int64              `db:"author_id" json:"author_id"`
	Title     string             `db:"title" json:"title"`
	Body      pgtype.Text        `db:"body" json:"body"`
	Views     int64              `db:"views" json:"views"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
