// Package search implements the DataSet search DSL on top of metaquery.
//
// A search string ("john status:active, !inactive") is parsed into an AST and
// compiled against a Builder's output columns into a single composite
// metaquery.Filter, which is ANDed into the wrapped query's WHERE clause via
// Apply. Type-driven defaults mean a zero Config already searches text columns
// (case-insensitive contains) and exact-matches typed columns by target; the
// Config only customizes overrides and virtual ("named") searches.
//
// Column kinds map to default predicates: plain text → contains (global);
// int/float → comparison/range (targeted); enum and other specialized text-like
// types (uuid, inet, ...) → exact match (targeted); bool → equality; time has
// no default (use TimeFn). "Plain text" is text/varchar/char/name/citext; any
// other DBType on a string column is treated as exact-match (see EnumFn).
//
// # Value operators
//
// Comparison, range, and wildcard operators are not part of the grammar — they
// ride inside the value string (`<`, `>`, `..`, `*` are valid value characters)
// and are interpreted during compilation (operators.go). Numeric columns
// understand them by default: "score:>=90", "score:10..99", "score:..50". Use
// TimeFn for date columns and WildcardFn for glob text ("name:foo*"); both are
// Fns assigned via Config.Fields. ParseValueOp exposes the primitive for custom
// Fns.
//
// # Grammar
//
// The lexer/parser are generated by ANTLR 4.13.2 from the .g4 files in
// grammar/, which are copies of the single source of truth in the sibling
// `dataset` project (../dataset/src/main/antlr4). Keeping one grammar for both
// the Kotlin and Go targets guarantees parse fidelity. Regenerate with
// `make antlr` after editing the grammar copies. The generated *.go files carry
// a "Code generated ... DO NOT EDIT." header and must never be hand-edited.
//
// # Safety
//
//   - Target names resolve against the Builder's whitelisted output columns; an
//     unresolved `field:` never reaches SQL as an identifier (it falls back to a
//     global literal term).
//   - All user values are bound parameters (? placeholders renumbered at Build),
//     never interpolated into SQL text.
package search
