// Package search implements the DataSet search DSL on top of metaquery.
//
// A search string ("john status:active, !inactive") is parsed into an AST and
// compiled against a Builder's output columns into a single composite
// metaquery.Filter, which is ANDed into the wrapped query's WHERE clause via
// Apply. Type-driven defaults mean a zero Config already searches text columns
// (case-insensitive contains) and exact-matches typed columns by target; the
// Config only customizes overrides and virtual ("named") searches.
//
// # Grammar
//
// The lexer/parser are generated by ANTLR 4.13.2 from the .g4 files in
// grammar/, which are copies of the single source of truth in the sibling
// `dataset` project (../dataset/src/main/antlr4). Keeping one grammar for both
// the Kotlin and Go targets guarantees parse fidelity. Regenerate with
// `make antlr` after editing the grammar copies. The generated *.go files carry
// a "Code generated ... DO NOT EDIT." header and must never be hand-edited.
//
// # Safety
//
//   - Target names resolve against the Builder's whitelisted output columns; an
//     unresolved `field:` never reaches SQL as an identifier (it falls back to a
//     global literal term).
//   - All user values are bound parameters (? placeholders renumbered at Build),
//     never interpolated into SQL text.
package search
