// Package metaquery provides runtime metadata types and a CTE-based query
// builder for queries generated by sqlc-go-codegen-metaquery.
//
// A generated Query value captures the column/arg shape of a sqlc query plus
// its original SQL text. Wrap one with Wrap() to compose additional filters,
// ordering, pagination, grouping, and aggregations on top without rewriting
// the original SQL — the original is embedded verbatim as a CTE.
package metaquery

// Dialect selects the placeholder syntax the Builder emits for filters,
// aggregations, and other appended SQL fragments. The zero value
// (DialectPostgres) preserves prior behavior; DialectSQLite is required when
// the wrapped query targets SQLite via database/sql, where Postgres-style $N
// is not the conventional placeholder form.
type Dialect string

const (
	DialectPostgres Dialect = ""
	DialectSQLite   Dialect = "sqlite"
)

// Query is the per-query metadata emitted alongside sqlc's generated code.
type Query struct {
	Name    string   `json:"name"`
	Cmd     string   `json:"cmd"`
	SQL     string   `json:"sql"`
	Source  string   `json:"source,omitempty"`
	Dialect Dialect  `json:"dialect,omitempty"`
	Columns []Column `json:"columns,omitempty"`
	Args    []Arg    `json:"args,omitempty"`
	Table   *Table   `json:"table,omitempty"`
}

// Column describes one result column of a query or builder projection.
type Column struct {
	Name         string `json:"name"`
	OriginalName string `json:"original_name,omitempty"`
	GoType       string `json:"go_type,omitempty"`
	DBType       string `json:"db_type,omitempty"`
	NotNull      bool   `json:"not_null,omitempty"`
	IsArray      bool   `json:"is_array,omitempty"`
	Table        string `json:"table,omitempty"`
	TableAlias   string `json:"table_alias,omitempty"`
}

// Arg describes one positional argument of the underlying query.
type Arg struct {
	Position    int    `json:"position"`
	Name        string `json:"name,omitempty"`
	GoType      string `json:"go_type,omitempty"`
	DBType      string `json:"db_type,omitempty"`
	NotNull     bool   `json:"not_null,omitempty"`
	IsArray     bool   `json:"is_array,omitempty"`
	IsSqlcSlice bool   `json:"is_sqlc_slice,omitempty"`
}

// Table identifies the insert target for :copyfrom queries.
type Table struct {
	Catalog string `json:"catalog,omitempty"`
	Schema  string `json:"schema,omitempty"`
	Name    string `json:"name"`
}

// HasColumn reports whether name matches any column's Name or OriginalName.
func (q *Query) HasColumn(name string) bool {
	for i := range q.Columns {
		if q.Columns[i].Name == name || q.Columns[i].OriginalName == name {
			return true
		}
	}
	return false
}

// Op is a named string type for structured filter operators. Predefined
// constants (OpEq, OpILike, ...) are preferred over raw strings; the typed
// parameter catches op typos at compile time when callers use constants.
// Raw string literals still work due to untyped-constant assignability.
type Op string

const (
	OpEq        Op = "="
	OpNe        Op = "!="
	OpLt        Op = "<"
	OpLe        Op = "<="
	OpGt        Op = ">"
	OpGe        Op = ">="
	OpLike      Op = "LIKE"
	OpILike     Op = "ILIKE"
	OpIn        Op = "IN"
	OpIsNull    Op = "IS NULL"
	OpIsNotNull Op = "IS NOT NULL"
)

// Filter is a predicate applied to a wrapped query. It's bidirectional: pass
// it into the builder via ApplyFilter to add WHERE/HAVING clauses, and read it
// back from Meta.Where/Meta.Having after execution to inspect what was
// applied (e.g. for rendering active filters in a UI).
//
// Use exactly one of:
//   - (Column, Op, Value)   — structured; Column is whitelisted against the query's output columns.
//   - (Expr, Args)          — raw SQL fragment with ? placeholders (renumbered at Build time).
type Filter struct {
	Column string `json:"column,omitempty"`
	Op     Op     `json:"op,omitempty"`
	Value  any    `json:"value,omitempty"`
	Expr   string `json:"expr,omitempty"`
	Args   []any  `json:"args,omitempty"`
}

// IsExpr reports whether the filter is a raw expression (no Column).
func (f Filter) IsExpr() bool { return f.Expr != "" }

// OrderBy is one ORDER BY entry. Structured form uses Column+Dir; raw form
// uses Expr.
type OrderBy struct {
	Column string    `json:"column,omitempty"`
	Dir    Direction `json:"dir,omitempty"`
	Expr   string    `json:"expr,omitempty"`
}

// PageRequest describes a pagination + total-count request. Size of 0 means
// no LIMIT. Total=true causes a second COUNT(*) query to populate
// Pagination.Total when the builder is executed.
type PageRequest struct {
	Page  int  `json:"page,omitempty"`
	Size  int  `json:"size,omitempty"`
	Total bool `json:"total,omitempty"`
}

// Pagination is the applied pagination state returned in Meta.
type Pagination struct {
	Limit  int   `json:"limit,omitempty"`
	Offset int   `json:"offset,omitempty"`
	Total  int64 `json:"total,omitempty"` // -1 if not computed
}

// Meta is the envelope describing a builder's output shape and the filters
// that were applied. Safe to JSON-serialize as the body of an API response.
type Meta struct {
	Columns    []Column    `json:"columns"`
	Pagination *Pagination `json:"pagination,omitempty"`
	Where      []Filter    `json:"where,omitempty"`
	Having     []Filter    `json:"having,omitempty"`
	GroupBy    []string    `json:"group_by,omitempty"`
	OrderBy    []OrderBy   `json:"order_by,omitempty"`
}

// Result is the untyped envelope from mqpgx.Run — each row is a positional
// []any matching Meta.Columns.
type Result struct {
	Data [][]any `json:"data"`
	Meta Meta    `json:"meta"`
}

// TypedResult is the typed envelope from mqpgx.Scan[T].
type TypedResult[T any] struct {
	Data []T  `json:"data"`
	Meta Meta `json:"meta"`
}
