// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Author struct {
	ID        int64          `db:"id" json:"id"`
	Name      string         `db:"name" json:"name"`
	Bio       sql.NullString `db:"bio" json:"bio"`
	CreatedAt time.Time      `db:"created_at" json:"created_at"`
}

type Post struct {
	ID        int64          `db:"id" json:"id"`
	AuthorID  int64          `db:"author_id" json:"author_id"`
	Title     string         `db:"title" json:"title"`
	Body      sql.NullString `db:"body" json:"body"`
	Views     int64          `db:"views" json:"views"`
	CreatedAt time.Time      `db:"created_at" json:"created_at"`
}
