// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name, bio) VALUES (?, ?) RETURNING id, name, bio, created_at
`

type CreateAuthorParams struct {
	Name string         `db:"name" json:"name"`
	Bio  sql.NullString `db:"bio" json:"bio"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, arg.Name, arg.Bio)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (author_id, title, body, views)
VALUES (?, ?, ?, ?)
RETURNING id, author_id, title, body, views, created_at
`

type CreatePostParams struct {
	AuthorID int64          `db:"author_id" json:"author_id"`
	Title    string         `db:"title" json:"title"`
	Body     sql.NullString `db:"body" json:"body"`
	Views    int64          `db:"views" json:"views"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.AuthorID,
		arg.Title,
		arg.Body,
		arg.Views,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.Views,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllAuthors = `-- name: DeleteAllAuthors :exec
DELETE FROM authors
`

// metaquery: off
func (q *Queries) DeleteAllAuthors(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAuthors)
	return err
}

const deleteAllPosts = `-- name: DeleteAllPosts :exec
DELETE FROM posts
`

// metaquery: off
// (Seed/cleanup only; no builder/metadata needed.)
func (q *Queries) DeleteAllPosts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllPosts)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, bio, created_at
FROM authors
WHERE id = ?
`

func (q *Queries) GetAuthor(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, bio, created_at
FROM authors
ORDER BY name
`

func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, author_id, title, body, views, created_at
FROM posts
ORDER BY created_at DESC
`

func (q *Queries) ListPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.Views,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsWithAuthor = `-- name: ListPostsWithAuthor :many
SELECT p.id, p.author_id, p.title, p.body, p.views, p.created_at, a.name AS author_name
FROM posts p
JOIN authors a ON a.id = p.author_id
ORDER BY p.created_at DESC
`

type ListPostsWithAuthorRow struct {
	ID         int64          `db:"id" json:"id"`
	AuthorID   int64          `db:"author_id" json:"author_id"`
	Title      string         `db:"title" json:"title"`
	Body       sql.NullString `db:"body" json:"body"`
	Views      int64          `db:"views" json:"views"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
	AuthorName string         `db:"author_name" json:"author_name"`
}

func (q *Queries) ListPostsWithAuthor(ctx context.Context) ([]ListPostsWithAuthorRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsWithAuthor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsWithAuthorRow
	for rows.Next() {
		var i ListPostsWithAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.Views,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
