// Code generated by sqlc-go-codegen-metaquery. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"github.com/iodesystems/sqlc-go-codegen-metaquery/metaquery"
)

var _ = metaquery.Query{}

var MetaCreateAuthor = metaquery.Query{
	Name:    "CreateAuthor",
	Cmd:     ":one",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL:     `INSERT INTO authors (name, bio) VALUES (?, ?) RETURNING id, name, bio, created_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "authors"},
		{Name: "name", OriginalName: "name", GoType: "string", DBType: "TEXT", NotNull: true, Table: "authors"},
		{Name: "bio", OriginalName: "bio", GoType: "sql.NullString", DBType: "TEXT", Table: "authors"},
		{Name: "created_at", OriginalName: "created_at", GoType: "time.Time", DBType: "DATETIME", NotNull: true, Table: "authors"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "name", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 2, Name: "bio", GoType: "sql.NullString", DBType: "TEXT"},
	},
	Table: &metaquery.Table{Name: "authors"},
}

// WrapCreateAuthor returns a metaquery.Builder over MetaCreateAuthor, pre-bound with typed arguments.
func WrapCreateAuthor(arg CreateAuthorParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaCreateAuthor, arg.Name, arg.Bio)
}

// CreateAuthorCols gives typed, name-safe access to CreateAuthor's output columns.
var CreateAuthorCols = struct {
	ID        metaquery.IntCol
	Name      metaquery.TextCol
	Bio       metaquery.AnyCol
	CreatedAt metaquery.TimeCol
}{
	ID:        metaquery.NewIntCol("id"),
	Name:      metaquery.NewTextCol("name"),
	Bio:       metaquery.NewAnyCol("bio"),
	CreatedAt: metaquery.NewTimeCol("created_at"),
}

var MetaCreatePost = metaquery.Query{
	Name:    "CreatePost",
	Cmd:     ":one",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `INSERT INTO posts (author_id, title, body, views)
VALUES (?, ?, ?, ?)
RETURNING id, author_id, title, body, views, created_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "posts"},
		{Name: "author_id", OriginalName: "author_id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "posts"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "TEXT", NotNull: true, Table: "posts"},
		{Name: "body", OriginalName: "body", GoType: "sql.NullString", DBType: "TEXT", Table: "posts"},
		{Name: "views", OriginalName: "views", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "posts"},
		{Name: "created_at", OriginalName: "created_at", GoType: "time.Time", DBType: "DATETIME", NotNull: true, Table: "posts"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "author_id", GoType: "int64", DBType: "INTEGER", NotNull: true},
		{Position: 2, Name: "title", GoType: "string", DBType: "TEXT", NotNull: true},
		{Position: 3, Name: "body", GoType: "sql.NullString", DBType: "TEXT"},
		{Position: 4, Name: "views", GoType: "int64", DBType: "INTEGER", NotNull: true},
	},
	Table: &metaquery.Table{Name: "posts"},
}

// WrapCreatePost returns a metaquery.Builder over MetaCreatePost, pre-bound with typed arguments.
func WrapCreatePost(arg CreatePostParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaCreatePost, arg.AuthorID, arg.Title, arg.Body, arg.Views)
}

// CreatePostCols gives typed, name-safe access to CreatePost's output columns.
var CreatePostCols = struct {
	ID        metaquery.IntCol
	AuthorID  metaquery.IntCol
	Title     metaquery.TextCol
	Body      metaquery.AnyCol
	Views     metaquery.IntCol
	CreatedAt metaquery.TimeCol
}{
	ID:        metaquery.NewIntCol("id"),
	AuthorID:  metaquery.NewIntCol("author_id"),
	Title:     metaquery.NewTextCol("title"),
	Body:      metaquery.NewAnyCol("body"),
	Views:     metaquery.NewIntCol("views"),
	CreatedAt: metaquery.NewTimeCol("created_at"),
}

var MetaGetAuthor = metaquery.Query{
	Name:    "GetAuthor",
	Cmd:     ":one",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT id, name, bio, created_at
FROM authors
WHERE id = ?`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "authors"},
		{Name: "name", OriginalName: "name", GoType: "string", DBType: "TEXT", NotNull: true, Table: "authors"},
		{Name: "bio", OriginalName: "bio", GoType: "sql.NullString", DBType: "TEXT", Table: "authors"},
		{Name: "created_at", OriginalName: "created_at", GoType: "time.Time", DBType: "DATETIME", NotNull: true, Table: "authors"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "id", GoType: "int64", DBType: "INTEGER", NotNull: true},
	},
}

// WrapGetAuthor returns a metaquery.Builder over MetaGetAuthor, pre-bound with typed arguments.
func WrapGetAuthor(id int64) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetAuthor, id)
}

// GetAuthorCols gives typed, name-safe access to GetAuthor's output columns.
var GetAuthorCols = struct {
	ID        metaquery.IntCol
	Name      metaquery.TextCol
	Bio       metaquery.AnyCol
	CreatedAt metaquery.TimeCol
}{
	ID:        metaquery.NewIntCol("id"),
	Name:      metaquery.NewTextCol("name"),
	Bio:       metaquery.NewAnyCol("bio"),
	CreatedAt: metaquery.NewTimeCol("created_at"),
}

var MetaListAuthors = metaquery.Query{
	Name:    "ListAuthors",
	Cmd:     ":many",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT id, name, bio, created_at
FROM authors
ORDER BY name`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "authors"},
		{Name: "name", OriginalName: "name", GoType: "string", DBType: "TEXT", NotNull: true, Table: "authors"},
		{Name: "bio", OriginalName: "bio", GoType: "sql.NullString", DBType: "TEXT", Table: "authors"},
		{Name: "created_at", OriginalName: "created_at", GoType: "time.Time", DBType: "DATETIME", NotNull: true, Table: "authors"},
	},
}

// WARNING: ListAuthors ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListAuthors returns a metaquery.Builder over MetaListAuthors, pre-bound with typed arguments.
func WrapListAuthors() *metaquery.Builder {
	return metaquery.Wrap(&MetaListAuthors)
}

// ListAuthorsCols gives typed, name-safe access to ListAuthors's output columns.
var ListAuthorsCols = struct {
	ID        metaquery.IntCol
	Name      metaquery.TextCol
	Bio       metaquery.AnyCol
	CreatedAt metaquery.TimeCol
}{
	ID:        metaquery.NewIntCol("id"),
	Name:      metaquery.NewTextCol("name"),
	Bio:       metaquery.NewAnyCol("bio"),
	CreatedAt: metaquery.NewTimeCol("created_at"),
}

var MetaListPosts = metaquery.Query{
	Name:    "ListPosts",
	Cmd:     ":many",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT id, author_id, title, body, views, created_at
FROM posts
ORDER BY created_at DESC`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "posts"},
		{Name: "author_id", OriginalName: "author_id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "posts"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "TEXT", NotNull: true, Table: "posts"},
		{Name: "body", OriginalName: "body", GoType: "sql.NullString", DBType: "TEXT", Table: "posts"},
		{Name: "views", OriginalName: "views", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "posts"},
		{Name: "created_at", OriginalName: "created_at", GoType: "time.Time", DBType: "DATETIME", NotNull: true, Table: "posts"},
	},
}

// WARNING: ListPosts ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListPosts returns a metaquery.Builder over MetaListPosts, pre-bound with typed arguments.
func WrapListPosts() *metaquery.Builder {
	return metaquery.Wrap(&MetaListPosts)
}

// ListPostsCols gives typed, name-safe access to ListPosts's output columns.
var ListPostsCols = struct {
	ID        metaquery.IntCol
	AuthorID  metaquery.IntCol
	Title     metaquery.TextCol
	Body      metaquery.AnyCol
	Views     metaquery.IntCol
	CreatedAt metaquery.TimeCol
}{
	ID:        metaquery.NewIntCol("id"),
	AuthorID:  metaquery.NewIntCol("author_id"),
	Title:     metaquery.NewTextCol("title"),
	Body:      metaquery.NewAnyCol("body"),
	Views:     metaquery.NewIntCol("views"),
	CreatedAt: metaquery.NewTimeCol("created_at"),
}

var MetaListPostsWithAuthor = metaquery.Query{
	Name:    "ListPostsWithAuthor",
	Cmd:     ":many",
	Source:  "query.sql",
	Dialect: metaquery.DialectSQLite,
	SQL: `SELECT p.id, p.author_id, p.title, p.body, p.views, p.created_at, a.name AS author_name
FROM posts p
JOIN authors a ON a.id = p.author_id
ORDER BY p.created_at DESC`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "posts"},
		{Name: "author_id", OriginalName: "author_id", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "posts"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "TEXT", NotNull: true, Table: "posts"},
		{Name: "body", OriginalName: "body", GoType: "sql.NullString", DBType: "TEXT", Table: "posts"},
		{Name: "views", OriginalName: "views", GoType: "int64", DBType: "INTEGER", NotNull: true, Table: "posts"},
		{Name: "created_at", OriginalName: "created_at", GoType: "time.Time", DBType: "DATETIME", NotNull: true, Table: "posts"},
		{Name: "author_name", OriginalName: "name", GoType: "string", DBType: "TEXT", NotNull: true, Table: "authors"},
	},
}

// WARNING: ListPostsWithAuthor ends in a top-level ORDER BY. Wrapping re-applies
// ordering at runtime, so .ApplyOrder(...) produces a doubled, nested sort
// that can defeat index use. Drop ORDER BY from the query and order via
// .ApplyOrder(...) instead. See benchmark/README.md.
// WrapListPostsWithAuthor returns a metaquery.Builder over MetaListPostsWithAuthor, pre-bound with typed arguments.
func WrapListPostsWithAuthor() *metaquery.Builder {
	return metaquery.Wrap(&MetaListPostsWithAuthor)
}

// ListPostsWithAuthorCols gives typed, name-safe access to ListPostsWithAuthor's output columns.
var ListPostsWithAuthorCols = struct {
	ID         metaquery.IntCol
	AuthorID   metaquery.IntCol
	Title      metaquery.TextCol
	Body       metaquery.AnyCol
	Views      metaquery.IntCol
	CreatedAt  metaquery.TimeCol
	AuthorName metaquery.TextCol
}{
	ID:         metaquery.NewIntCol("id"),
	AuthorID:   metaquery.NewIntCol("author_id"),
	Title:      metaquery.NewTextCol("title"),
	Body:       metaquery.NewAnyCol("body"),
	Views:      metaquery.NewIntCol("views"),
	CreatedAt:  metaquery.NewTimeCol("created_at"),
	AuthorName: metaquery.NewTextCol("name"),
}
